services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blockchain-network

  backend:
    build:
      dockerfile: ./Dockerfile.dev
      context: packages/backend
    env_file:
      - packages/backend/.env
    depends_on:
      - postgres
    volumes:
      - ./packages/backend:/backend
      - uploads_data:/backend/uploads
    ports:
      - 3000:3000
      - 5555:5555
    restart: unless-stopped
    networks:
      - blockchain-network
    labels:
      - dev.orbstack.domains=api.blockchain.local

volumes:
  db_data: {}
  uploads_data: {}

networks:
  blockchain-network:
  xrpld-network:
