[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
juniper = "0.16"
env_logger = "0.10"
log = "0.4"
diesel = { version = "2.2.7", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"
chrono = "0.4"